name: Setup Qt
description: Install Qt on machine
runs:
  using: composite
  steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version:      6.5.*
        target:       desktop
        setup-python: false
   