name: Setup Qt
description: Install Qt on machine
inputs:
  host:
    description: 'Host operating system'
    required: false
    type: string
    default: linux

runs:
  using: composite
  steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version:      6.5.*
        host:         ${{ inputs.host }}
   